
set t_Co=256
syntax on
set background=dark
colorscheme qsicol

if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.

set nu				" display line number
set autoindent		" auto indentation
set incsearch		" incremental search
set nobackup		" no *~ backup files
set copyindent		" copy the previous indentation on autoindenting
set ignorecase		" ignore case when searching
set smartcase		" ignore case if search pattern is all lowercase,case-sensitive otherwise
set smarttab		" insert tabs on the start of a line according to context
set mouse=a		    " Enable mouse usage (all modes)


set nocompatible	" not compatible with the old-fashion vi mode
set bs=2		    " allow backspacing over everything in insert mode
set history=50		" keep 50 lines of command line history
set ruler		    " show the cursor position all the time
set autoread		" auto read when file is changed from outside

set expandtab        "replace <TAB> with spaces
set softtabstop=4 
set shiftwidth=4 

hi User1 ctermfg=15    ctermbg=28 
hi User2 ctermfg=28    ctermbg=19 
hi User3 ctermfg=15    ctermbg=19 
hi User4 ctermfg=19    ctermbg=54 
hi User5 ctermfg=15    ctermbg=54
hi User6 ctermfg=54    ctermbg=240 
hi User7 ctermfg=15    ctermbg=240
hi User8 ctermfg=255   ctermbg=240
hi User9 ctermfg=000   ctermbg=255

set laststatus=2
"set statusline=%<%f\ %m%=\ %h%r\ %-19([%p%%]\ %3l,%02c%03V%)%y
"set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P
set statusline=%<%1*
set statusline+=%t\ 
set statusline+=%2*▶%3*
set statusline+=%h%m%r
set statusline+=%4*▶%5*
set statusline+=%{fugitive#statusline()}
set statusline+=%6*▶%7*
set statusline+=%=%-14.(%l,%c%V%)\ 
set statusline+=%8*◀%9*
set statusline+=%P

highlight StatusLine term=bold,reverse cterm=bold,reverse

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

inoremap {<CR> {<CR><END><CR>}<UP><END>
inoremap qq  <ESC>

" taglist plugin
nnoremap <silent> <F4> :TlistToggle<CR>  
let Tlist_Show_One_File = 1
let Tlist_Auto_Open = 1
let Tlist_Auto_Update = 1
let Tlist_Exit_OnlyWindow = 1

